// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: data_update_service.proto

package protolca

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateSystemRequest_DefaultProviders int32

const (
	CreateSystemRequest_Prefer CreateSystemRequest_DefaultProviders = 0
	CreateSystemRequest_Ignore CreateSystemRequest_DefaultProviders = 1
	CreateSystemRequest_Only   CreateSystemRequest_DefaultProviders = 2
)

// Enum value maps for CreateSystemRequest_DefaultProviders.
var (
	CreateSystemRequest_DefaultProviders_name = map[int32]string{
		0: "Prefer",
		1: "Ignore",
		2: "Only",
	}
	CreateSystemRequest_DefaultProviders_value = map[string]int32{
		"Prefer": 0,
		"Ignore": 1,
		"Only":   2,
	}
)

func (x CreateSystemRequest_DefaultProviders) Enum() *CreateSystemRequest_DefaultProviders {
	p := new(CreateSystemRequest_DefaultProviders)
	*p = x
	return p
}

func (x CreateSystemRequest_DefaultProviders) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateSystemRequest_DefaultProviders) Descriptor() protoreflect.EnumDescriptor {
	return file_data_update_service_proto_enumTypes[0].Descriptor()
}

func (CreateSystemRequest_DefaultProviders) Type() protoreflect.EnumType {
	return &file_data_update_service_proto_enumTypes[0]
}

func (x CreateSystemRequest_DefaultProviders) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateSystemRequest_DefaultProviders.Descriptor instead.
func (CreateSystemRequest_DefaultProviders) EnumDescriptor() ([]byte, []int) {
	return file_data_update_service_proto_rawDescGZIP(), []int{1, 0}
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelType ModelType `protobuf:"varint,1,opt,name=model_type,json=modelType,proto3,enum=protolca.ModelType" json:"model_type,omitempty"`
	Id        string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_update_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_update_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_data_update_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteRequest) GetModelType() ModelType {
	if x != nil {
		return x.ModelType
	}
	return ModelType_UNDEFINED_MODEL_TYPE
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateSystemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The (reference of the) process from which the product system should be
	// generated. This will be the reference process of the product system
	// with upstream and downstream processes added recursively.
	Process *Ref `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	// Indicates how default providers of product inputs and waste outputs
	// should be considered during the linking. `only` means that only
	// product inputs and waste outputs should be linked that have a
	// default provider and that this default provider is used. `prefer`
	// means that a default provider is used during the linking if there
	// are multiple options. `ignore` means that the default providers
	// have no specific role.
	DefaultProviders CreateSystemRequest_DefaultProviders `protobuf:"varint,2,opt,name=default_providers,json=defaultProviders,proto3,enum=protolca.services.CreateSystemRequest_DefaultProviders" json:"default_providers,omitempty"`
	// When there are multiple provider processes available for linking a
	// product input or waste output the `preferred_type` indicates which
	// type of process (LCI results or unit processes) should be preferred
	// during the linking.
	PreferredType ProcessType `protobuf:"varint,3,opt,name=preferred_type,json=preferredType,proto3,enum=protolca.ProcessType" json:"preferred_type,omitempty"`
}

func (x *CreateSystemRequest) Reset() {
	*x = CreateSystemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_update_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemRequest) ProtoMessage() {}

func (x *CreateSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_update_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemRequest.ProtoReflect.Descriptor instead.
func (*CreateSystemRequest) Descriptor() ([]byte, []int) {
	return file_data_update_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSystemRequest) GetProcess() *Ref {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *CreateSystemRequest) GetDefaultProviders() CreateSystemRequest_DefaultProviders {
	if x != nil {
		return x.DefaultProviders
	}
	return CreateSystemRequest_Prefer
}

func (x *CreateSystemRequest) GetPreferredType() ProcessType {
	if x != nil {
		return x.PreferredType
	}
	return ProcessType_UNDEFINED_PROCESS_TYPE
}

var File_data_update_service_proto protoreflect.FileDescriptor

var file_data_update_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6c, 0x63, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6f, 0x6c, 0x63,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6c, 0x63, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x98, 0x02, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x63, 0x61, 0x2e,
	0x52, 0x65, 0x66, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x64, 0x0a, 0x11,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c,
	0x63, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x10, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x3c, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6c, 0x63, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x34, 0x0a, 0x10, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x4f, 0x6e, 0x6c, 0x79, 0x10, 0x02, 0x32, 0xd7, 0x01, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x03,
	0x50, 0x75, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x63, 0x61, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x74, 0x1a,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x63, 0x61, 0x2e, 0x52, 0x65, 0x66, 0x12, 0x42,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6c, 0x63, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x4c, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x6c, 0x63, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x63, 0x61, 0x2e, 0x52, 0x65, 0x66,
	0x42, 0x4b, 0x0a, 0x16, 0x6f, 0x72, 0x67, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x6c, 0x63, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x0f, 0x44, 0x61, 0x74, 0x61,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0a, 0x2e,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x63, 0x61, 0xaa, 0x02, 0x11, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x4c, 0x43, 0x41, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_update_service_proto_rawDescOnce sync.Once
	file_data_update_service_proto_rawDescData = file_data_update_service_proto_rawDesc
)

func file_data_update_service_proto_rawDescGZIP() []byte {
	file_data_update_service_proto_rawDescOnce.Do(func() {
		file_data_update_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_update_service_proto_rawDescData)
	})
	return file_data_update_service_proto_rawDescData
}

var file_data_update_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_update_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_update_service_proto_goTypes = []interface{}{
	(CreateSystemRequest_DefaultProviders)(0), // 0: protolca.services.CreateSystemRequest.DefaultProviders
	(*DeleteRequest)(nil),                     // 1: protolca.services.DeleteRequest
	(*CreateSystemRequest)(nil),               // 2: protolca.services.CreateSystemRequest
	(ModelType)(0),                            // 3: protolca.ModelType
	(*Ref)(nil),                               // 4: protolca.Ref
	(ProcessType)(0),                          // 5: protolca.ProcessType
	(*DataSet)(nil),                           // 6: protolca.services.DataSet
	(*empty.Empty)(nil),                       // 7: google.protobuf.Empty
}
var file_data_update_service_proto_depIdxs = []int32{
	3, // 0: protolca.services.DeleteRequest.model_type:type_name -> protolca.ModelType
	4, // 1: protolca.services.CreateSystemRequest.process:type_name -> protolca.Ref
	0, // 2: protolca.services.CreateSystemRequest.default_providers:type_name -> protolca.services.CreateSystemRequest.DefaultProviders
	5, // 3: protolca.services.CreateSystemRequest.preferred_type:type_name -> protolca.ProcessType
	6, // 4: protolca.services.DataUpdateService.Put:input_type -> protolca.services.DataSet
	1, // 5: protolca.services.DataUpdateService.Delete:input_type -> protolca.services.DeleteRequest
	2, // 6: protolca.services.DataUpdateService.CreateProductSystem:input_type -> protolca.services.CreateSystemRequest
	4, // 7: protolca.services.DataUpdateService.Put:output_type -> protolca.Ref
	7, // 8: protolca.services.DataUpdateService.Delete:output_type -> google.protobuf.Empty
	4, // 9: protolca.services.DataUpdateService.CreateProductSystem:output_type -> protolca.Ref
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_update_service_proto_init() }
func file_data_update_service_proto_init() {
	if File_data_update_service_proto != nil {
		return
	}
	file_olca_proto_init()
	file_commons_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_data_update_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_update_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSystemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_update_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_update_service_proto_goTypes,
		DependencyIndexes: file_data_update_service_proto_depIdxs,
		EnumInfos:         file_data_update_service_proto_enumTypes,
		MessageInfos:      file_data_update_service_proto_msgTypes,
	}.Build()
	File_data_update_service_proto = out.File
	file_data_update_service_proto_rawDesc = nil
	file_data_update_service_proto_goTypes = nil
	file_data_update_service_proto_depIdxs = nil
}
